### ISSUE TITLE
indexError: string index out of range

### ISSUE THREAD

**Issue by pureGavin** [SeHwa/mipsrop-for-ida7#1]
![image](https://user-images.githubusercontent.com/45478229/97880608-58444d00-1d5c-11eb-820e-8461a9d00894.png)
what should i do?

**Comment by pureGavin** [comment]
it is a libc.so.0 i just wanna find a rop chain, but the plugin is not work

**Comment by pureGavin** [comment]
well... there is an other issus come up... 
![image](https://user-images.githubusercontent.com/45478229/97944680-28597180-1d7d-11eb-978c-db8d4789bc17.png)

**Comment by SeHwa** [comment]
This code is obsolete.

Please clone the [original repository](https://github.com/tacnetsol/ida/tree/master/plugins/mipsrop).
The original repository seems to have updated the code related to this issue.

Good luck.
